# Generated by Django 4.2.1 on 2024-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='type',
            field=models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], default='N', max_length=20),
        ),
    ]
